[package]
name = "example_tokio_tradeclient"
version = { workspace = true }
edition = "2024"

[dependencies]
thiserror = { workspace = true }
rustyfix = { path = "../../crates/rustyfix", features = ["fix42"] }
inquire = { workspace = true }
slog = { workspace = true }
slog-term = { workspace = true }
slog-async = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true, features = ["net", "io-util", "macros"] }
tokio-util = { workspace = true, features = ["compat"] }

[build-dependencies]
rustyfix = { path = "../../crates/rustyfix", features = ["fix42", "codegen"] }
