[workspace]
members = ["crates/*"] # "examples/*", "tests/*"
resolver = "2"

[workspace.package]
authors = ["cognitive-glitch", "Team Rusty Trading", "Filippo Neysofu Costa"]
version = "0.7.2"
edition = "2024"
homepage = "https://github.com/rusty-trading/rusty-fix-engine"
repository = "https://github.com/rusty-trading/rusty-fix-engine"
description = "FIX & FAST (FIX Adapted for STreaming) in pure Rust"
publish = true
readme = "README.md"
keywords = ["fix", "fast", "protocol", "finance", "fintech"]
categories = ["network-programming", "parser-implementations", "encoding"]
license = "Apache-2.0"

[workspace.lints.rust]
rust-2024-compatibility = "warn"
rust-2024-incompatible-pat = "warn"

[workspace.dependencies]
rustc-hash = "2.1"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
strip = true
debug = false
overflow-checks = false
rpath = false

[profile.release.build-override]
opt-level = 3
codegen-units = 1
[profile.release.package."*"]
opt-level = 3

[profile.dev]
incremental = false

[profile.dev.build-override]
# Helps with compile times for macro-heavy code. See
# <https://corrode.dev/blog/tips-for-faster-rust-compile-times/.
opt-level = 1
