[workspace]
members = ["crates/*", "examples/*", "tests/*"]
resolver = "2"

[workspace.package]
authors = ["cognitive-glitch", "Team Rusty Trading", "Filippo Neysofu Costa"]
version = "0.7.0"
edition = "2024"
homepage = "https://github.com/rusty-engine/rustyfix"
repository = "https://github.com/rusty-engine/rustyfix"
description = "FIX & FAST (FIX Adapted for STreaming) in pure Rust"
publish = true
readme = "README.md"
keywords = ["fix", "fast", "protocol", "finance", "fintech"]
categories = ["network-programming", "parser-implementations", "encoding"]
license = "Apache-2.0"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"
strip = true

[profile.dev.build-override]
# Helps with compile times for macro-heavy code. See
# <https://corrode.dev/blog/tips-for-faster-rust-compile-times/.
opt-level = 1
