[package]
name = "example_json_encoding"
version = { workspace = true }
edition = "2024"

[dependencies]
rustyfix = { path = "../../crates/rustyfix", features = [
    "json-encoding",
    "fix42",
] }
