[package]
name = "example_tcp_sofh_tokio_codec"
version = "0.1.0"
edition = "2024"

[dependencies]
rustysofh = { path = "../../crates/rustysofh", features = [
    "utils-tokio-codec",
] }
futures-util = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true, features = ["codec"] }
