[package]
name = "tokio_fix_decoder_example"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
rustyfix = { path = "../../crates/rustyfix", features = ["utils-tokio"] }
rustyfix-dictionary = { path = "../../crates/rustyfix-dictionary", features = [
    "fix42",
] }
tokio = { workspace = true }
tokio-util = { workspace = true, features = ["codec"] }
futures-util = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[[bin]]
name = "fix_server"
path = "src/server.rs"

[[bin]]
name = "fix_client"
path = "src/client.rs"
