[package]
name = "example_coinbase_codegen"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
rustyfix = { path = "../../crates/rustyfix" }

[build-dependencies]
rustyfix = { path = "../../crates/rustyfix", features = ["codegen"] }
